WebBooks/urls.py
from django.contrib import admin
from django.urls import path, re_path, include
from catalog import views

urlpatterns = [
    path('', views.index, name='index'),
    re_path(r'^authors/$', views.AuthorListView.as_view(), name='authors'),
    re_path(r'^books/$', views.BookListView.as_view(), name='books'),
    re_path(r'^book/(?P<pk>\d+)$', views.BookDetailView.as_view(), name='book-detail'),
    path('admin/', admin.site.urls),
]

urlpatterns += [
    path('accounts/', include('django.contrib.auth.urls')),
]

catalog/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User
from datetime import date


class Genre(models.Model):
    name = models.CharField(max_length=200,
                            help_text='Введите жанр книги',
                            verbose_name='Жанр книги')

    def __str__(self):
        return self.name


class Language(models.Model):
    name = models.CharField(max_length=20,
                            help_text='Введите язык книги',
                            verbose_name='Язык книги')

    def __str__(self):
        return self.name


class Author(models.Model):
    first_name = models.CharField(max_length=100,
                                  help_text='Введите фамилию автора',
                                  verbose_name='Имя автора')

    last_name = models.CharField(max_length=100,
                                 help_text='Введите фамилию автора',
                                 verbose_name='Фамилию автора')

    date_of_birth = models.DateField(help_text='Введите дату рождения',
                                     verbose_name='Дата рождения',
                                     null=True, blank=True)

    date_of_death = models.DateField(help_text='Введите дату смерти',
                                     verbose_name='Дата смерти',
                                     null=True, blank=True)

    def __str__(self):
        return self.last_name


class Book(models.Model):
    title = models.CharField(max_length=200,
                             help_text='Введите назвние книги',
                             verbose_name='Название книги')

    genre = models.ForeignKey('Genre', on_delete=models.CASCADE,
                              help_text='Выберите жанр для книги',
                              verbose_name='Жанр книги', null=True)

    language = models.ForeignKey('Language', on_delete=models.CASCADE,
                                 help_text='Выберите язык книги',
                                 verbose_name='Язык книги', null=True)

    author = models.ManyToManyField('Author',
                                    help_text='Выберите автора книги',
                                    verbose_name='Автор книги')

    summary = models.TextField(max_length=1000,
                               help_text='Введите краткое описание книги',
                               verbose_name='Аннотация книги')

    isbn = models.CharField(max_length=13,
                            help_text='Должно содержать 13 символов',
                            verbose_name='ISBN книги')

    def display_author(self):
        return ', '.join([author.last_name for author in self.author.all()])

    display_author.short_description = 'Авторы'

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('book-detail', args=[str(self.id)])


class Status(models.Model):
    name = models.CharField(max_length=20,
                            help_text='Введите статус экземпляра книги',
                            verbose_name='Статус экземпляра книги')

    def __str__(self):
        return self.name


class BookInstance(models.Model):
    book = models.ForeignKey('Book', on_delete=models.CASCADE, null=True)
    inv_number = models.CharField(max_length=20, null=True,
                                  help_text='Введите инвентарный номер экзмепляр',
                                  verbose_name='Инвентарный номер')
    imprint = models.CharField(max_length=200,
                               help_text='Введение издательства и год выпуска',
                               verbose_name='Издательство')
    status = models.ForeignKey('Status', on_delete=models.CASCADE, null=True,
                               help_text='Изменить состояние экзмепляра',
                               verbose_name='Статус экземпляра книги')

    due_back = models.DateField(null=True, blank=True,
                                help_text='Ввведите конец строка статуса',
                                verbose_name='Дата окончания статуса')

    borrower = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True,
                                 verbose_name="Заказчик", help_text="Выберите заказчика книги")

    @property
    def is_overdue(self):
        if self.due_back and date.today() > self.due_back:
            return True
        return False

    def __str__(self):
        return f'{self.inv_number} {self.book} {self.status}'

catalog/views.py
from django.shortcuts import render
from django.views import generic

from .models import Book, Author, BookInstance, Genre


def index(request):
    num_books = Book.objects.all().count()
    num_instances = BookInstance.objects.all().count()
    num_instances_available = \
        BookInstance.objects.filter(status__exact=2).count()
    num_author = Author.objects.count()
    num_visits = request.session.get('num_visits', 0)
    request.session['num_visits'] = num_visits + 1

    return render(request, "index.html",
                  context={'num_books': num_books,
                           'num_instances': num_instances,
                           'num_instances_available': num_instances_available,
                           'num_author': num_author,
                           'num_visits': num_visits}
                  )

class AuthorListView(generic.ListView):
    model = Author
    paginate_by = 3

class BookListView(generic.ListView):
    model = Book
    paginate_by = 3


class BookDetailView(generic.DetailView):
    model = Book

catalog/templates/base_generic.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% block title %} <title>Мир книг</title>{% endblock %}
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/ bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/ jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/ js/bootstrap.min.js"></script>

    {%  load static %}
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
    {%  block head %}
        <img src="{% static 'images/logotip.png' %}"
         style="width:100px; height:100px;" align="absmiddle">
        <font size="7", color="blue">Сайт "Мир книг"</font>
    {%  endblock %}
</head>
<body>
    <div class="container-fluid">
        <div class="row">
            <div class="col-sm-2">
                {%block sidebar%}
                <ul class="sidebar-nav">
                    <li><a href="{% url 'index' %}">Главная страница</a></li>
                    <li><a href="{% url 'books' %}">Все книги</a></li>
                    <li><a href="{% url 'authors' %}">Все авторы</a></li>
                {% if user.is_authenticated %}
                    <li>Пользователь: {{ user.get_username }} </li>
                    <li><a href="{% url 'logout' %}?next={{request.path}}">Logout</a></li>
                    {% else %}
                        <li><a href="{% url 'login' %}?next={{request.path}}">Login</a></li>
                    {% endif %}
                </ul>
                {% endblock %}
            </div>
            <div class="col-sm-10 ">
                {% block content %}
                {% endblock %}

                {%block pagination %}
                    {%if is_paginated %}
                <div class="pagination">
                    <span class="step-links">
                        {% if page_obj.has_previous %}
                            <a href="?page={{ page_obj.previous_page_number }}">Предыдущая</a>
                        {% endif %}

                        <span class="current">
                            Страница {{ page_obj.number }} из {{ page_obj.paginator.num_pages }}.
                        </span>

                        {% if page_obj.has_next %}
                            <a href="?page={{ page_obj.next_page_number }}">Следующая</a>
                        {% endif %}
                    </span>
                </div>
                {% endif %}
                {% endblock %}

                {% block footer %}
                    {% block copyright %}
                <p>Copyright ООО "Люди и книги", 2022 "Все права защищены"</p>
                    {% endblock %}
                {% endblock %}
            </div>
        </div>
    </div>

</body>
</html>

catalog/templates/catalog/author_list.html
{% extends "base_generic.html"%}

{% block content %}
    <h1>Список авторов</h1>
    {% if author_list %}
        {% for author in author_list.all %}
        <p>{{ author.first_name }} {{author.last_name }},
            <strong>Родился-</strong> {{ author.date_of_birth }},
            <strong>Умер-</strong> {{author.date_of_death}}</p>
        {% endfor %}
    {% else %}
        <p>Список авторов пуст</p>
    {% endif %}
{% endblock %}

catalog/templates/catalog/book_detail.html
{% extends "base_generic.html" %}

{% block content %}
<h1> Название книги: {{ book.title }}</h1>

<p><strong>Жанр: </strong> {{ book.genre}} </p>
<p><strong>Аннотации: </strong> {{ book.summary }} </p>
<p><strong>ISBN: </strong> {{ book.isbn }} </p>
<p><strong>Язык: </strong> {{ book.language }} </p>
    {% for author in book.author.all %}
        <p><strong>Автор: </strong>
            <a href=""> {{ author.first_name }}
                {{ author.last_name }}</a> </p>

    {% endfor %}
<div style="margin-left:20px; margin-top:20px">
    <h4>Количество экзамепляров книг</h4>
    {% for copy in book.bookinstance_set.all %}
    <hr><p class="{% if copy.status == 1 %} text-success
       {% elif copy.status == 2 %} text-danger
       {% else %} text-warning
       {% endif %}"> {{  copy.get_status_display }} </p>
    <p><strong>Издaтeльcтвo:</strong> {{copy.imprint}}</p>
    <p class="text-muted"><strong>Инвeнтapный нoмep:</strong> {{copy.id}}</p>
    <p><strong>Cтaтyc экземпляра книги:</strong> {{copy.status}}</p>
    {%  endfor %}
</div>
{% endblock %}
<p><strong>Aвтop:</strong> <a  href="">{{ author.first_name }} {{author.last_name }}</a></p>

catalog/templates/catalog/book_list.html
{% extends "base_generic.html" %}

{% block content %}
    <h1>Список книг</h1>
    {% if book_list %}
    <ul>
        {% for book in book_list %}
        <li>
            <a href="{{ books.get_absolute_url }}"> {{ book.title }}</a>
                     ({{ book.genre }})
        </li>
        {% endfor %}
    </ul>
    {% else %}
        <p> Список книг пуст</p>
    {% endif %}
{% endblock %}

catalog/templates/index.html
{% extends "base_generic.html" %}

{% block content %}
<h1>Главная страница</h1>
    <p>Добро пожаловать в <em>Мир книг</em>, Это простой веб сайт, написанный на Django. Разработанный мной в качестве
        учебного примера</p>
<h2>Динмаический контент</h2>
    <p> База данных сайта Мир книг содержит следующее количество записей: </p>
    <ul>
        <li><strong>Количество книг:</strong> {{num_books}}</li>
        <li><strong>Количество экземпляров книг:</strong> {{num_instances}} </li>
        <li><strong>Количество экземпляров книг на заказе:</strong> {{num_instances_available }} </li>
        <li><strong>Количество авторов книг:</strong> {{num_author}} </li>
    </ul>
    <p>Количество посещений страницы - {{num_visits }}</p>
{% endblock %}